{
 "title": "Cache clearing",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "flush all events",
   "type": "timeseries",
   "description": "Indicates that all caches are being flushed by a plugin. This is an operation which should not be triggered by external plugins and can lead to product slowdowns\n\nDetermine who invoked this, then reach out to the app vendor and flag this issue to them. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(com_atlassian_jira_metrics_Count{category00=\"cacheManager\",name=\"flushAll\",invokerPluginKey!=\"undefined\"}[5m])",
     "legendFormat": "{{invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "remove all events",
   "type": "timeseries",
   "description": "Indicates that a single cache has all of its entries removed. This may or may not cause slowdowns in products or plugins. \n\nCheck the frequency at which these cache removals occur and from which product. You can find out what plugin created the cache using the pluginKeyAtCreation tag. If excessive, consider reaching out to the app vendor and flag this issue to them. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(com_atlassian_jira_metrics_Count{category00=\"cache\",name=\"removeAll\",pluginKeyAtCreation!=\"undefined\"}[5m])",
     "legendFormat": "{{pluginKeyAtCreation}}"
    }
   ]
  },
  {
   "title": "plugin enabled/disabled events",
   "type": "timeseries",
   "description": "Measure how many times a plugin has been disabled since uptime.\n\nSome caches are cleared when plugin is disabled/ enabled and may have performance impact. If you see high counts, check the UPM or application logs to investigate which plugin is contributing to high counts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum without (instance) (com_atlassian_jira_metrics_Count{category00=\"plugin\",name=\"counter\",category01=\"enabled\"})",
     "legendFormat": "enabled"
    },
    {
     "expr": "sum without (instance) (com_atlassian_jira_metrics_Count{category00=\"plugin\",name=\"counter\",category01=\"disabled\"})",
     "legendFormat": "disabled"
    }
   ]
  },
  {
   "title": "reset events",
   "type": "timeseries",
   "description": "Indicates that a single entry in a cache has been reset. This may or may not cause slowdowns in products or plugins. \n\nCheck the frequency at which these cache resets occur and from which product. You can find out what plugin created the cache using the pluginKeyAtCreation tag. If excessive, consider reaching out to the app vendor and flag this issue to them. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(com_atlassian_jira_metrics_Count{category00=\"cachedReference\",name=\"reset\",pluginKeyAtCreation!=\"undefined\"}[5m])",
     "legendFormat": "{{pluginKeyAtCreation}}"
    }
   ]
  }
 ]
}