{
 "title": "Database load",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Relative load by API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "load using AO's EntityManager (mean - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long an AO operation (create, find, delete, deleteWithSQL, get, stream, count) that uses the Entity Manager takes.\n\nThe operation query might be long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum without (instance, entityType) (sum without (name) (com_atlassian_jira_metrics_Mean{category00=\"db\", category01=\"ao\", category02=\"entityManager\"}) * sum without (name) (com_atlassian_jira_metrics_Count{category00=\"db\", category01=\"ao\", category02=\"entityManager\"}))/10000)",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "load using AO's EntityManager (p99 - per node)",
   "type": "timeseries",
   "description": "Measures how long an AO operation (create, find, delete, deleteWithSQL, get, stream, count) that uses the Entity Manager takes.\n\nThe operation query might be long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum without (name,entityType) (com_atlassian_jira_metrics_99thPercentile{category00=\"db\", category01=\"ao\", category02=\"entityManager\"}))/1000",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  { "title": "AO's executeInTransaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "number of running queries using AO's execute in transaction",
   "type": "gauge",
   "description": "Measures how long an AO transaction takes, when executed inside the TransactionCallBack. This is mainly used by Confluence plugins.\n\nThe transaction can have many AO operations, it can be either there are too many operations or the query is long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, tag_taskName, tag_invokerPluginKey) (com_atlassian_jira_metrics_Value{category00=\"db\",category01=\"ao\",name=\"executeInTransaction\", tag_statistic=\"active\", tag_taskName!=\"undefined\"})"
    }
   ]
  },
  {
   "title": "queries running using AO's execute in transaction (cluster wide)",
   "type": "timeseries",
   "description": "Measures how long an AO transaction takes, when executed inside the TransactionCallBack. This is mainly used by Confluence plugins.\n\nThe transaction can have many AO operations, it can be either there are too many operations or the query is long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum without (instance) (com_atlassian_jira_metrics_Value{category00=\"db\",category01=\"ao\",name=\"executeInTransaction\", tag_statistic=\"active\", tag_taskName!=\"undefined\"})",
     "legendFormat": "{{ tag_invokerPluginKey }} - {{tag_taskName}} (task)"
    }
   ]
  },
  { "title": "SAL's executeInTransaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "number of running queries using SAL's execute in transaction",
   "type": "gauge",
   "description": "Measures how long an SAL transaction takes, when executed inside the DefaultTransactionalExecutor.\n\nThe transaction can have many SAL operations, it can be either there are too many operations or the query is long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, tag_taskName, tag_invokerPluginKey) (com_atlassian_jira_metrics_Value{category00=\"db\",category01=\"sal\",name=\"transactionalExecutor\", tag_statistic=\"active\"})"
    }
   ]
  },
  {
   "title": "queries running using SAL's execute in transaction",
   "type": "timeseries",
   "description": "Measures how long an SAL transaction takes, when executed inside the DefaultTransactionalExecutor.\n\nThe transaction can have many SAL operations, it can be either there are too many operations or the query is long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (instance) (com_atlassian_jira_metrics_Value{category00=\"db\",category01=\"sal\",name=\"transactionalExecutor\",tag_statistic=\"active\"})",
     "legendFormat": "{{ tag_invokerPluginKey }} - {{tag_taskName}} (task)"
    }
   ]
  },
  { "title": "AO upgrade tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Number of running AO upgrade tasks",
   "type": "gauge",
   "description": "Measures how long an App is taking to upgrade a part of the data that it stores in the database.\n\nUpgrade tasks happen when an App is both updated and enabled, during this time the App’s functionality will probably be unavailable, and it may temporarily increase load on the database and the node the upgrade task is running on.\n\nIf an App stores a lot of data in database then this may take a while to run, if possible, try to schedule upgrading Apps with large amounts of data in off-peak hours.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, tag_invokerPluginKey, tag_taskName) (com_atlassian_jira_metrics_Value{category00=\"db\", category01=\"ao\", name=\"upgradetask\", tag_statistic=\"active\"})"
    }
   ]
  },
  {
   "title": "running AO upgrade tasks",
   "type": "timeseries",
   "description": "Measures how long an App is taking to upgrade a part of the data that it stores in the database.\n\nUpgrade tasks happen when an App is both updated and enabled, during this time the App’s functionality will probably be unavailable, and it may temporarily increase load on the database and the node the upgrade task is running on.\n\nIf an App stores a lot of data in database then this may take a while to run, if possible, try to schedule upgrading Apps with large amounts of data in off-peak hours.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum without (instance) (com_atlassian_jira_metrics_Value{category00=\"db\", category01=\"ao\", name=\"upgradetask\", tag_statistic=\"active\"})",
     "legendFormat": "{{ tag_invokerPluginKey }} - {{tag_taskName}} (task)"
    }
   ]
  }
 ]
}