{
 "title": "Response times",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Web fragment evaluation times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "web fragment condition evaluation time (mean - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long web fragment condition will take to determine whether a web fragment should be displayed or not.\n\nWeb fragments conditions determine whether a link or a section on a page should be displayed. Slow web fragment conditions lead to slow page load times especially if they are not cached. Reach out to the app vendor responsible to flag and investigate. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, (sum without (instance) (com_atlassian_jira_metrics_Mean{category00=\"web\", category01=\"fragment\", name=\"condition\"}) / sum without (instance) (com_atlassian_jira_metrics_Count{category00=\"web\", category01=\"fragment\", name=\"condition\"})*1000))",
     "legendFormat": "{{tag_fromPluginKey}} - {{tag_conditionClassName}} (condition)"
    }
   ]
  },
  {
   "title": "web fragment condition evaluation time (p99 - per node)",
   "type": "timeseries",
   "description": "Measures how long web fragment condition will take to determine whether a web fragment should be displayed or not.\n\nWeb fragments conditions determine whether a link or a section on a page should be displayed. Slow web fragment conditions lead to slow page load times especially if they are not cached. Reach out to the app vendor responsible to flag and investigate. ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, com_atlassian_jira_metrics_99thPercentile{category00=\"web\", category01=\"fragment\", name=\"condition\"})",
     "legendFormat": "{{tag_fromPluginKey}} - {{tag_conditionClassName}} (condition)"
    }
   ]
  },
  { "title": "Soy web panel render times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Soy web panel response times (cluster-wide)",
   "type": "table",
   "description": "Measures how long a Soy Template web panel is taking to render.\n\nThe template renderer might be long-running. If there is a plugin with a slow Soy renderer it might be worth adding (tag__templateName) to the query and contacting the vendor responsible to investigate if long-running queries are expected.",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "topk(500, avg without (instance, tag_templateName) (com_atlassian_jira_metrics_Mean{name=\"webTemplateRenderer\",tag_templateRenderer=\"soy\"}) )"
    },
    {
     "expr": "sum without (instance, tag_templateName) (com_atlassian_jira_metrics_Count{name=\"webTemplateRenderer\",tag_templateRenderer=\"soy\"})"
    },
    {
     "expr": "max without (instance, tag_templateName) (com_atlassian_jira_metrics_99thPercentile{name=\"webTemplateRenderer\",tag_templateRenderer=\"soy\"})"
    }
   ]
  },
  {
   "title": "soy web panel response time (mean - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long a Soy Template web panel is taking to render.\n\nThe template renderer might be long running. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, (sum without (instance) (com_atlassian_jira_metrics_Mean{name=\"webTemplateRenderer\",tag_templateRenderer=\"soy\"}) / sum without (instance) (com_atlassian_jira_metrics_Count{name=\"webTemplateRenderer\", tag_templateRenderer=\"soy\"})))",
     "legendFormat": "{{tag_fromPluginKey}} - {{tag_templateName}} (template)"
    }
   ]
  },
  {
   "title": "soy web panel response time (p99 - per node) ",
   "type": "timeseries",
   "description": "Measures how long a Soy Template web panel is taking to render.\n\nThe template renderer might be long running. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, com_atlassian_jira_metrics_99thPercentile{name=\"webTemplateRenderer\",tag_templateRenderer=\"soy\"})",
     "legendFormat": "{{tag_fromPluginKey}} - {{tag_templateName}}__{{instance}} (template)"
    }
   ]
  },
  { "title": "Web panel render times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "velocity web panel response time (mean - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long an Atlassian Template web panel is taking to render.\n\nThe template renderer might be long running. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, (sum without (instance) (com_atlassian_jira_metrics_Mean{name=\"webTemplateRenderer\",tag_templateRenderer=\"velocity\"}) / sum without (instance) (com_atlassian_jira_metrics_Count{name=\"webTemplateRenderer\", tag_templateRenderer=\"velocity\"})))",
     "legendFormat": "{{tag_fromPluginKey}} - {{tag_templateName}} (template)"
    }
   ]
  },
  {
   "title": "velocity web panel response time (p99 - per node) ",
   "type": "timeseries",
   "description": "Measures how long an Atlassian Template web panel is taking to render.\n\nThe template renderer might be long running. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, com_atlassian_jira_metrics_99thPercentile{name=\"webTemplateRenderer\",tag_templateRenderer=\"velocity\"})",
     "legendFormat": "{{tag_fromPluginKey}} - {{tag_templateName}} (template)"
    }
   ]
  },
  { "title": "Web resource evaluation times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "web resource condition evaluation time (mean - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long web resource condition will take to determine whether a resource should be displayed or not.\n\nSlow web resource conditions lead to slow page load times especially if they are not cached. Reach out to the app vendor responsible to flag and investigate. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, (sum without (instance) (com_atlassian_jira_metrics_Mean{category00=\"web\", category01=\"resource\", name=\"condition\"}) / sum without (instance) (com_atlassian_jira_metrics_Count{category00=\"web\", category01=\"resource\", name=\"condition\"})*1000))",
     "legendFormat": "{{tag_fromPluginKey}} - {{tag_conditionClassName}} (condition)"
    }
   ]
  },
  {
   "title": "web resource condition evaluation time (p99 - per node)",
   "type": "timeseries",
   "description": "Measures how long web resource condition will take to determine whether a resource should be displayed or not.\n\nSlow web resource conditions lead to slow page load times especially if they are not cached. Reach out to the app vendor responsible to flag and investigate. ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, com_atlassian_jira_metrics_99thPercentile{category00=\"web\", category01=\"resource\", name=\"condition\"})",
     "legendFormat": "{{tag_fromPluginKey}} - {{tag_conditionClassName}} (condition)"
    }
   ]
  },
  { "title": "REST request times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Most requested endpoints & response time",
   "type": "table",
   "description": "Use this table to quickly identify the slowest calls and some outliers using the 99th percentile response time. Use this table to figure out which endpoint to investigate then correlate it with the other timeseries panels for more detailed diagnosis ",
   "gridPos": { "h": 26, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "topk(500, avg without (instance) (com_atlassian_jira_metrics_Mean{category00=\"http\", category01=\"rest\", name=\"request\"}))"
    },
    {
     "expr": "sum without (instance) (com_atlassian_jira_metrics_Count{category00=\"http\", category01=\"rest\", name=\"request\"})"
    },
    {
     "expr": "max without (instance) (com_atlassian_jira_metrics_99thPercentile{category00=\"http\", category01=\"rest\", name=\"request\"})"
    }
   ]
  },
  {
   "title": "http rest request time (mean - cluster wide)",
   "type": "timeseries",
   "description": "Measures HTTP requests of the REST APIs that uses the atlassian-rest module.\n\nCheck the frequency and duration of the rest requests. If excessive or very slow, consider reaching out to the app vendor and flag this issue to them.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, (sum without (instance) (com_atlassian_jira_metrics_Mean{category00=\"http\", category01=\"rest\", name=\"request\"}) / sum without (instance) (com_atlassian_jira_metrics_Count{category00=\"http\", category01=\"rest\", name=\"request\"})))",
     "legendFormat": "{{tag_fromPluginKey}} - {{tag_path}} (path)"
    }
   ]
  },
  {
   "title": "http rest request time (p99 - per node)",
   "type": "timeseries",
   "description": "Measures HTTP requests of the REST APIs that uses the atlassian-rest module.\n\nCheck the frequency and duration of the rest requests. If excessive or very slow, consider reaching out to the app vendor and flag this issue to the",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, com_atlassian_jira_metrics_99thPercentile{category00=\"http\", category01=\"rest\", name=\"request\"})",
     "legendFormat": "{{tag_fromPluginKey}} - {{tag_path}} (path)"
    }
   ]
  },
  {
   "title": "REST average response time per plugin",
   "type": "timeseries",
   "description": "A timeseries of plugins REST calls and their average response time regardless of which node they are running on",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg without (instance, tag_path, tag_action) (com_atlassian_jira_metrics_Mean{category00=\"http\",category01=\"rest\", name=\"request\"})",
     "legendFormat": "{{tag_fromPluginKey}}"
    }
   ]
  }
 ]
}