{
 "title": "ITA Dash",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "java_lang_Runtime_StartTime{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Recent Alerts",
   "type": "alertlist",
   "gridPos": { "h": 11, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{instance=\"localhost:2991\"}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{}[1m])",
     "legendFormat": "{{gc}} - {{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(java_lang_OperatingSystem_ProcessCpuLoad * 1000)",
     "legendFormat": "cpu load"
    }
   ]
  },
  {
   "title": "Heap Used %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(jvm_memory_bytes_used{area=\"heap\"}/jvm_memory_bytes_max{area=\"heap\"})",
     "legendFormat": "Used {{ area }}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{}[1m])",
     "legendFormat": "{{gc}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Blocked Threads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"BLOCKED\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "Tomcat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Tomcat Request Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_requestCount{}[1m])",
     "legendFormat": "{{name}} count - {{instance}}"
    },
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_errorCount{}[1m])",
     "legendFormat": "{{name}} error - {{instance}}"
    }
   ]
  },
  {
   "title": "Tomcat Threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( Catalina_ThreadPool_currentThreadCount / Catalina_ThreadPool_maxThreads) * 100",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Tomcat Request Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_processingTime{}[1m]) / increase(Catalina_GlobalRequestProcessor_requestCount{}[1m])",
     "legendFormat": "{{name}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Tomcat Sessions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Catalina_Manager_activeSessions",
     "legendFormat": "active sessions: {{instance}}"
    },
    {
     "expr": "Catalina_Manager_rejectedSessions",
     "legendFormat": "rejected sessions: {{instance}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Connection Pool Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(com_atlassian_jira_BasicDataSource_NumActive{connectionpool=\"connections\"} / com_atlassian_jira_BasicDataSource_MaxTotal{connectionpool=\"connections\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_atlassian_jira_BasicDataSource_NumActive{connectionpool=\"connections\"}",
     "legendFormat": "active - {{instance}}"
    },
    {
     "expr": "com_atlassian_jira_BasicDataSource_NumIdle{connectionpool=\"connections\"}",
     "legendFormat": "idle - {{instance}}"
    }
   ]
  },
  {
   "title": "Reads / Writes",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(com_atlassian_jira_db_reads_invocation_count[1m])",
     "legendFormat": "reads - {{instance}}"
    },
    {
     "expr": "rate(com_atlassian_jira_db_writes_invocation_count[1m])",
     "legendFormat": "writes - {{instance}}"
    }
   ]
  }
 ]
}