{
 "title": "REST requests",
 "time": { "from": "now/w", "to": "now/w" },
 "panels": [
  {
   "title": "Most requested endpoints & response time",
   "type": "table",
   "description": "Use this table to quickly identify the slowest calls and some outliers using the 99th percentile response time. Use this table to figure out which endpoint to investigate then correlate it with the other timeseries panels for more detailed diagnosis ",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(500, avg without (instance) (com_atlassian_jira_metrics_Mean{category00=\"http\", category01=\"rest\", name=\"request\"}))"
    },
    {
     "expr": "sum without (instance) (com_atlassian_jira_metrics_Count{category00=\"http\", category01=\"rest\", name=\"request\"})"
    },
    {
     "expr": "avg without (instance) (com_atlassian_jira_metrics_99thPercentile{category00=\"http\", category01=\"rest\", name=\"request\"})"
    }
   ]
  },
  {
   "title": "HTTP REST Request Time (mean - cluster wide)",
   "type": "timeseries",
   "description": "Measures the time HTTP requests of the REST APIs that uses the atlassian-rest module.\n\nCheck the frequency and duration of the rest requests. If excessive or very slow, consider reaching out to the app vendor and flag this issue to them.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10, (sum without (instance) (com_atlassian_jira_metrics_Mean{category00=\"http\", category01=\"rest\", name=\"request\"}) / sum without (instance) (com_atlassian_jira_metrics_Count{category00=\"http\", category01=\"rest\", name=\"request\"})))",
     "legendFormat": "{{tag_fromPluginKey}} - {{tag_path}}"
    }
   ]
  },
  {
   "title": "Plugins REST response time",
   "type": "timeseries",
   "description": "A timeseries of plugins REST calls and their average response time regardless of which node they are running on",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg without (instance, tag_path, tag_action) (com_atlassian_jira_metrics_Mean{category00=\"http\",category01=\"rest\", name=\"request\"})",
     "legendFormat": "{{tag_fromPluginKey}}"
    }
   ]
  }
 ]
}